#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Sherlock Tailscale Setup — encrypted tunnel for telemetry
# Run on BOTH the Sherlock machine and the monitoring server.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; GOLD='\033[0;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${GOLD}[!]${NC} $*"; }
error() { echo -e "${RED}[x]${NC} $*"; }

OS="$(uname -s)"
ARCH="$(uname -m)"

# ── Install Tailscale ────────────────────────────────────────────────────────

install_tailscale() {
  if command -v tailscale &>/dev/null; then
    info "Tailscale already installed: $(tailscale version | head -1)"
    return 0
  fi

  case "$OS" in
    Darwin)
      if command -v brew &>/dev/null; then
        info "Installing Tailscale via Homebrew..."
        brew install --cask tailscale
      else
        error "Homebrew not found. Install Tailscale from https://tailscale.com/download/mac"
        exit 1
      fi
      ;;
    Linux)
      info "Installing Tailscale via official script..."
      curl -fsSL https://tailscale.com/install.sh | sh
      ;;
    *)
      error "Unsupported OS: $OS"
      exit 1
      ;;
  esac

  info "Tailscale installed."
}

# ── Authenticate ─────────────────────────────────────────────────────────────

connect_tailscale() {
  info "Checking Tailscale status..."
  STATUS=$(tailscale status 2>&1 || true)

  if echo "$STATUS" | grep -q "Tailscale is stopped"; then
    info "Starting Tailscale..."
    if [ "$OS" = "Darwin" ]; then
      open -a Tailscale
      sleep 3
    else
      sudo systemctl enable --now tailscaled
      sleep 2
    fi
  fi

  # Check if already logged in
  if tailscale status &>/dev/null; then
    HOSTNAME=$(tailscale status --self --json 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('Self',{}).get('HostName','?'))" 2>/dev/null || echo "?")
    IP=$(tailscale ip -4 2>/dev/null || echo "?")
    info "Already connected to tailnet."
    info "  Hostname: $HOSTNAME"
    info "  Tailscale IP: $IP"
  else
    warn "Not authenticated. Opening login..."
    tailscale up --hostname "sherlock-$(hostname -s | tr '[:upper:]' '[:lower:]')"
    IP=$(tailscale ip -4 2>/dev/null || echo "pending")
    info "Authenticated. Tailscale IP: $IP"
  fi
}

# ── Configure for Sherlock telemetry ─────────────────────────────────────────

configure_agent() {
  local CONF_DIR="$(cd "$(dirname "$0")" && pwd)"
  local CONF_FILE="${CONF_DIR}/agent.conf"
  local TS_IP
  TS_IP=$(tailscale ip -4 2>/dev/null || echo "100.x.x.x")

  echo ""
  info "Configuring Sherlock telemetry agent..."

  # Prompt for telemetry server IP
  read -rp "  Telemetry server Tailscale IP (e.g. 100.64.0.1): " SERVER_IP
  SERVER_IP="${SERVER_IP:-100.64.0.1}"

  # Generate agent token if not set
  if [ -f "$CONF_FILE" ] && grep -q "AGENT_TOKEN=" "$CONF_FILE"; then
    warn "agent.conf already exists — preserving AGENT_TOKEN."
  else
    TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    info "Generated agent token: $TOKEN"
    warn "Copy this SAME token to the telemetry server's server.conf AGENT_TOKEN."
  fi

  # Write/update agent.conf
  cat > "$CONF_FILE" << CONF
# Sherlock Telemetry Agent Configuration
# Generated by setup-tailscale.sh on $(date)

# Remote telemetry server — must be reachable via Tailscale
TELEMETRY_SERVER_URL=http://${SERVER_IP}:9200

# Shared secret — MUST match the server's AGENT_TOKEN
AGENT_TOKEN=${TOKEN:-$(grep AGENT_TOKEN "$CONF_FILE" 2>/dev/null | cut -d= -f2)}

# Display name for this node in the dashboard
NODE_NAME=sherlock-$(hostname -s | tr '[:upper:]' '[:lower:]')

# Heartbeat interval (seconds)
HEARTBEAT_INTERVAL=30

# This node's Tailscale IP (auto-detected)
NODE_IP=${TS_IP}
CONF

  info "Wrote $CONF_FILE"
  echo ""
  info "Setup complete. Next steps:"
  echo "  1. Copy the AGENT_TOKEN to the telemetry server's server.conf"
  echo "  2. On the telemetry server, run: python3 server/server.py"
  echo "  3. On this machine, run:        python3 agent.py"
  echo "  Or install as a launchd/systemd service (plist included)."
}

# ── Main ─────────────────────────────────────────────────────────────────────

main() {
  echo ""
  echo "  ╔══════════════════════════════════════╗"
  echo "  ║  Sherlock Tailscale Tunnel Setup      ║"
  echo "  ╚══════════════════════════════════════╝"
  echo ""

  install_tailscale
  connect_tailscale

  echo ""
  read -rp "Configure telemetry agent on this machine? [y/N] " CONFIGURE
  if [[ "$CONFIGURE" =~ ^[Yy]$ ]]; then
    configure_agent
  else
    info "Skipped agent configuration. Tailscale is connected."
  fi

  echo ""
  info "Tailscale IP: $(tailscale ip -4 2>/dev/null || echo 'pending')"
  info "Done."
}

main "$@"
